#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum class WINMODE { FULL, WIN };

	enum class PROTOTYPE { GAMEOBJECT, COMPONENT };

	enum class RENDERID { PRIORITY, SHADOW, NONBLEND, NONLIGHT, BLEND, END };

	enum class RENDERUIID {BACK, MIDDLE, FRONT, END};

	enum class STATE { RIGHT, UP, LOOK, POSITION, END };

	enum class D3DTS { VIEW, PROJ, END };

	enum class PROJ_TYPE { PERSPEC, ORTHO, END };

	enum class LIGHT { DIRECTIONAL, POINT, END };

	enum class MODEL { NONANIM, ANIM, MAP, END };

	enum class NAVI_POINT { A, B, C, END };

	enum class NAVI_LINE { AB, BC, CA, END };

	enum class COLLIDER { AABB, OBB, SPHERE, END };

	enum class DIMB { LBUTTON, RBUTTON, WHEEL, END };

	enum class DIMM { X, Y, WHEEL, END };

	enum class DEFERRED { DEBUG, DIRECTIONAL, POINT, COMBINED, BRIGHT, BLUR, COMPSITE, END };

	enum class ANIM_EVENT_PHASE { POINT, BEGIN, TICK, END };
	
	enum class MTEX_TYPE { NONE, DIFFUSE, SPECULAR, AMBIENT, EMISSIVE, HEIGHT, NORMALS, SHININESS, 
		OPACITY, DISPLACEMENT, LIGHTMAP, REFLECTION, BASECOLOR, NORMALCAMERA, 
		EMISSIONCOLOR, METALNESS, ROUGHNESS, AO, UNKNOWN,
		SHEEN, CLEARCOAT, TRANSMISSION, MAYABASE, MAYASPECULAR, MAYASPECULARCOLOR, MAYASPECULARROUGHNESS,
		ANISOTROPY, GLTF_MERALLICROUGHNESS
	};

}
#endif // Engine_Enum_h__
