#pragma once

#ifndef PROFILE_ENABLE
#define PROFILE_ENABLE 1
#endif

#include "Engine_Defines.h"

NS_BEGIN(Engine)

enum class EPROFILE_CPU_SECTION : _uint
{
	FRAME = 0,
	UPDATE,
	RENDER_TOTAL,
	ENV_CULLING,
	PRESENT,
	END
};

enum class EPROFILE_COUNTER : _uint
{
	RENDER_SUBMITTED_TOTAL = 0,
	RENDER_SUBMITTED_PRIORITY,
	RENDER_SUBMITTED_SHADOW,
	RENDER_SUBMITTED_NONBLEND,
	RENDER_SUBMITTED_DECAL,
	RENDER_SUBMITTED_NONLIGHT,
	RENDER_SUBMITTED_BLEND,
	RENDER_SUBMITTED_UI,

	FRUSTUM_TESTED,
	FRUSTUM_VISIBLE,
	FRUSTUM_CULLED,
	FRUSTUM_FAIL_OPEN_INVALID_VIEW,
	FRUSTUM_FAIL_OPEN_INVALID_BOUNDS,

	DISTANCE_TESTED,
	DISTANCE_VISIBLE,
	DISTANCE_CULLED,
	DISTANCE_FAIL_OPEN_INVALID_CAMERA,
	DISTANCE_FAIL_OPEN_INVALID_BOUNDS,
	DISTANCE_FAIL_OPEN_INVALID_DISTANCE,

	ENV_VISIBLE_MAIN,
	ENV_VISIBLE_SHADOW,

	ENV_INSTANCE_BATCH_SUBMITTED,
	ENV_INSTANCE_SUBMITTED,
	ENV_INSTANCE_RENDERED,
	ENV_INSTANCE_FALLBACK,

	END
};

struct PROFILER_FRAME_SNAPSHOT
{
	_uint64 iFrameIndex = {};
	_float fDeltaTime = 0.f;
	_float fFrameMs = 0.f;
	_float fFPS = 0.f;
	_float fAvgFPS = 0.f;

	double CpuMs[ETOUI(EPROFILE_CPU_SECTION::END)] = {};
	_uint Counters[ETOUI(EPROFILE_COUNTER::END)] = {};
	TEXTURE_HUB_STATS TextureHub = {};
};

NS_END