#pragma once
#include "Boss_Gorilla.h"
#include "Boss_GorillaRush.h"
#include "Boss_Gorilla_Body.h"
#include "CutsceneGorilla.h"
#include "GorillaNamePlate.h"
#include "Boss_Gorilla_RockHole.h"
#include "Boss_Cage.h"
#include "Boss_Cage_Body.h"
#include "Cage_WaddleDee.h"

#include "Boss_Armadillo.h"
#include "Boss_Armadillo_Body.h"
#include "Projectile_Partner.h"
#include "Boss_Armadillo_Cage.h"

#include "Boss_Leopard.h"
#include "Boss_Leopard_Body.h"
#include "Projectile_Nail.h"

#include "Boss_Metaknight.h"
#include "Boss_Metaknight_Body.h"
#include "Boss_Metaknight_Sword.h"
#include "Boss_Metaknight_ReplicaSword.h"
#include "Boss_Metaknight_Mant.h"
#include "Boss_Metaknight_EscapeMant.h"
#include "Projectile_MoonShot.h"
#include "Excalibur.h"
#include "Excalibur_Body.h"
#include "Excalibur_GetIt.h"
#include "MetaknightNamePlate.h"
#include "AttackDecal.h"
#include "Projectile_Rock.h"